# 전역 설정 파일
# 모든 웹사이트에 공통으로 적용되는 설정

# 브라우저 설정
browser:
  headless: false
  window_size: "1920x1080"
  user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
  timeout: 10
  retry_count: 3

# 로깅 설정
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {message}"
  file: "logs/automation/rpa_automation.log"
  rotation: "1 day"
  retention: "30 days"

# 경로 설정
paths:
  data_input: "./data/input/"
  data_output: "./data/output/"
  logs: "./logs/"
  templates: "./data/templates/"

# 성능 설정
performance:
  wait_time: 1
  page_load_timeout: 30
  implicit_wait: 10

# 에러 처리 설정
error_handling:
  max_retries: 3
  retry_delay: 5
  continue_on_error: false

# 알림 설정
notifications:
  enabled: false
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: ""
    sender_password: ""
  slack:
    webhook_url: "" 